device: cuda
batch_size: 2
lr: 0.0001
weight_decay: 0.00001
LABEL_ALL_TOKENS: True
SLIDING_WIN_SIZE: 1
HAVE_PRE: False
MODEL_PATH: xlm-roberta-large-finetuned-conll03-english  
TRAIN_DATA_DIR: train_data/per_big/
PRE_LABEL: B-PER
CEN_LABEL: I-PER
DEFAULT_LABEL: I-PER
ADD_SPECIAL_TOKENS: True
USE_SPECIAL_TOKENS: False
WORD_TRUE_TOR: 0.4
WORD_FALSE_TOR: 1
MAX_SEQUENCE: 50


