LABEL_ALL_TOKENS: True
SLIDING_WIN_SIZE: 5
HAVE_PRE: True
MODEL_PATH: Davlan/bert-base-multilingual-cased-ner-hrl 
DATA_FILE_PATH: eval_data/eval_data.json
PRE_LABEL: B-PER
CEN_LABEL: I-PER
DEFAULT_LABEL: PER
ADD_SPECIAL_TOKENS: True
