python fine_tune_train_v3.py \
    --model_name_or_path dslim/bert-base-NER \
    --output_dir ./test-ner \
    --do_train True \
    --do_eval True \
    --overwrite_output_dir True \
    --train_file ./train_data/per_big_new/train0000.json \
    --validation_file ./train_data/per_big_new/valid0000.json \
    --auto_find_batch_size True \
    --num_train_epochs 3 \
    --save_strategy "epoch" \
    --save_steps 50 \
    --logging_first_step True \
    --logging_steps 10 \
    --evaluation_strategy "steps" \
    --eval_steps 10 \
    --include_inputs_for_metrics True \
    --include_inputs_for_metrics True \
    --per_device_train_batch_size 8 \
    --fp16_full_eval True \
    --return_entity_level_metrics True \
    --learning_rate 0.000001 \
    --label_all_tokens True \
    --ignore_mismatched_sizes True
    
